---
networks:
  frontend:
    external: true
services:
  uptimekuma:
    image: louislam/uptime-kuma:1.23.13-alpine
    container_name: uptimekuma
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: "true"
      traefik.http.services.uptimekuma-prod-1.loadbalancer.server.port: "3001"
      traefik.http.services.uptimekuma-prod-1.loadbalancer.server.scheme: "http"
      traefik.http.routers.uptimekuma-prod-1-https.entrypoints: "websecure"
      traefik.http.routers.uptimekuma-prod-1-https.rule: "Host(`uptimekuma.srv-prod-1.home.unixvextor.com`)"
      traefik.http.routers.uptimekuma-prod-1-https.tls: "true"
      traefik.http.routers.uptimekuma-prod-1-https.tls.certresolver: "cloudflare" 
    networks:
      - frontend
    restart: unless-stopped
