---
networks:
  forntend:
    external: true
  backend:
    external: true
volumes:
  mariadb-data:
services:
  mariadb:
    container_name: db-prod-1
    image: mariadb:10.6.17
    ports:
      - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - forntend
      - backend
    restart: unless-stopped