version: "3"

services:
  app:
    container_name: sonarqube-send-notification-srv
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.services.sonarqube-srv.loadbalancer.server.port: "3000"
      traefik.http.services.sonarqube-srv.loadbalancer.server.scheme: "http"
      traefik.http.routers.sonarqube-srv-https.entrypoints: "websecure"
      traefik.http.routers.sonarqube-srv-https.rule: "Host(`sonarqube-noti-srv.srv-demo-1.home.unixvextor.com`)"
      traefik.http.routers.sonarqube-srv-https.tls: "true"
      traefik.http.routers.sonarqube-srv-https.tls.certresolver: "cloudflare"
    networks:
      - backend
      - frontend
networks:
  backend:
    external: true
  frontend:
    external: true
