name: Update Sonarqube Notification Docker Container

on:
     push:
          branches:
               - main
          paths:
               - 'sonarqube-notification/*'
jobs:
     deploy:
          runs-on: "self-hosted"
          steps:
               - name: Checkout
                 uses: actions/checkout@v2

               - name: Clear Old Docker Container
                 run: |
                      docker stop sonarqube-send-notification-srv || true
                      docker rm sonarqube-send-notification-srv || true

               - name: Build Image And Run Docker Container
                 run: |
                      cd sonarqube-notification 
                      docker compose up -d